package main

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	toml "github.com/pelletier/go-toml/v2"
	"github.com/spf13/cobra"

	"github.com/HyperMarble/hyperray/internal/bridges"
	"github.com/HyperMarble/hyperray/internal/semanticir"
)

// newBridgesGenCmd generates the probe files the spec implies -- one per
// rule-group, named so per-row attribution works without any mapping file:
// wit_<operation>__<key>.py watches the rows of that operation matching that
// key. Hyperray writes the whole file from the compiled spec: the rule IDs, the
// conditions, the required outcomes, and the observation contract. The one
// line hyperray cannot know -- how to call the system under test -- is a TODO the
// task author fills, because that knowledge is the task's, not hyperray's.
// Existing files are never touched.
func newBridgesGenCmd() *cobra.Command {
	return &cobra.Command{
		Use:          "bridges-gen <task-dir>",
		Hidden:       true,
		Short:        "Generate the probe files the spec implies; author fills one calling line each",
		Args:         cobra.ExactArgs(1),
		SilenceUsage: true,
		RunE: func(cmd *cobra.Command, args []string) error {
			taskDir, err := filepath.Abs(args[0])
			if err != nil {
				return err
			}
			language, sourceRoot := taskLanguage(taskDir)
			task, err := compileTaskDir(taskDir)
			if err != nil {
				return err
			}
			outcomes := map[string]semanticir.ObservableOutcome{}
			for _, outcome := range task.Outcomes {
				outcomes[outcome.ID] = outcome
			}
			bridgesDir := filepath.Join(taskDir, "bridges")
			if err := os.MkdirAll(bridgesDir, 0o755); err != nil {
				return err
			}
			// One probe per (operation, key): rules sharing a key share a
			// probe. Raise-rows are excluded -- the message breaker already
			// covers them without any probe.
			groups := map[string][]semanticir.RequirementCase{}
			for _, requirement := range task.Requirements {
				for _, key := range probeKeys(requirement, outcomes) {
					name := requirement.OperationID + "__" + key
					groups[name] = append(groups[name], requirement)
				}
			}
			// Probes are fully generated: each one feeds the row's own values
			// to the operation's entry file and prints what came back. The
			// entry file -- one per operation, a few lines -- is the only
			// authored piece, the same trust surface Grounding already is.
			probes, entries, existing := 0, 0, 0
			if language != "python" {
				written, err := writeCompiledLanguageHarness(cmd, language, sourceRoot, bridgesDir)
				if err != nil {
					return err
				}
				entries += written
			}
			seenOps := map[string]bool{}
			for name, requirements := range groups {
				requirement := requirements[0]
				operation := requirement.OperationID
				if language == "python" {
					entryPath := filepath.Join(bridgesDir, "entry_"+operation+".py")
					if _, err := os.Stat(entryPath); err != nil && !seenOps[operation] {
						if err := os.WriteFile(entryPath, []byte(bridges.PythonEntryStub(operation, requirement.Conditions)), 0o755); err != nil {
							return err
						}
						entries++
						fmt.Fprintf(cmd.OutOrStdout(), "entry stub  entry_%s.py (author fills ~5 lines, once)\n", operation)
					}
				}
				seenOps[operation] = true
				extension, body := ".py", ""
				if language == "python" {
					body = bridges.PythonProbe(operation, requirement.Conditions)
				} else {
					extension = ".sh"
					body = bridges.WrapperScript(language, operation, requirement.Conditions)
				}
				path := filepath.Join(bridgesDir, "wit_"+name+extension)
				if _, err := os.Stat(path); err == nil {
					existing++
					continue
				}
				if err := os.WriteFile(path, []byte(body), 0o755); err != nil {
					return err
				}
				probes++
			}
			fmt.Fprintf(cmd.OutOrStdout(), "\n%d probe(s) generated by hyperray, %d already existed, %d entry stub(s) for the author\n", probes, existing, entries)
			return nil
		},
	}
}

// probeKeys names the probe(s) that watch one rule: its required string
// label, or for concrete-outcome rules each condition value, so the file
// name alone carries the attribution.
func probeKeys(requirement semanticir.RequirementCase, outcomes map[string]semanticir.ObservableOutcome) []string {
	for _, outcomeID := range requirement.RequiredOutcomes {
		outcome := outcomes[outcomeID]
		if outcome.Kind == semanticir.OutcomeReturn && outcome.Value != nil && outcome.Value.Type == semanticir.TypeString {
			return []string{outcome.Value.String}
		}
		// A raise-row's probe watches the error path; all combos sharing the
		// message share one probe, named by the message itself.
		if outcome.Kind == semanticir.OutcomeRaise && outcome.Message != "" {
			return []string{slug(outcome.Message)}
		}
	}
	var keys []string
	for _, name := range sortedKeys(requirement.Conditions) {
		keys = append(keys, requirement.Conditions[name])
	}
	if len(keys) == 0 {
		keys = []string{"any"}
	}
	return keys[:1]
}

func slug(text string) string {
	var out []rune
	for _, r := range strings.ToLower(text) {
		switch {
		case r >= 'a' && r <= 'z' || r >= '0' && r <= '9':
			out = append(out, r)
		case len(out) > 0 && out[len(out)-1] != '-':
			out = append(out, '-')
		}
	}
	return strings.Trim(string(out), "-")
}

func sortedKeys(values map[string]string) []string {
	var keys []string
	for key := range values {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	return keys
}

// taskLanguage reads the task's language and source root from the task config;
// absent config means a Python task.
func taskLanguage(taskDir string) (string, string) {
	var cfg oneshotConfig
	raw, err := os.ReadFile(taskConfigPath(taskDir))
	if err != nil {
		return "python", ""
	}
	if err := toml.Unmarshal(raw, &cfg); err != nil {
		return "python", ""
	}
	language := cfg.Oneshot.Language
	if language == "" {
		language = "python"
	}
	return language, cfg.Oneshot.SourceRoot
}

// writeCompiledLanguageHarness writes the shared harness and entry stub for
// a Rust or C++ task. Rust sources live in the crate's examples/ directory
// so cargo links them against the code under test; C++ sources live beside
// the wrappers in bridges/. Existing files are never touched.
func writeCompiledLanguageHarness(cmd *cobra.Command, language, sourceRoot, bridgesDir string) (int, error) {
	type file struct {
		path, body string
		stub       bool
	}
	var files []file
	if language == "rust" {
		if sourceRoot == "" {
			return 0, fmt.Errorf("bridges-gen: rust probes need source_root in hyperray.toml (the crate to link against)")
		}
		examples := filepath.Join(sourceRoot, "examples")
		if err := os.MkdirAll(examples, 0o755); err != nil {
			return 0, err
		}
		files = []file{
			{filepath.Join(examples, "hyperray_probes.rs"), bridges.RustHarness(), false},
			{filepath.Join(examples, "hyperray_entry.rs"), bridges.RustEntryStub(), true},
		}
	} else {
		files = []file{
			{filepath.Join(bridgesDir, "hyperray_probes.cpp"), bridges.CppHarness(), false},
			{filepath.Join(bridgesDir, "hyperray_entry.cpp"), bridges.CppEntryStub(), true},
		}
	}
	stubs := 0
	for _, f := range files {
		if _, err := os.Stat(f.path); err == nil {
			continue
		}
		if err := os.WriteFile(f.path, []byte(f.body), 0o644); err != nil {
			return stubs, err
		}
		if f.stub {
			stubs++
			fmt.Fprintf(cmd.OutOrStdout(), "entry stub  %s (author fills, once)\n", filepath.Base(f.path))
		}
	}
	return stubs, nil
}
