// ARM64 section parsing tests read the generated public artifact directly.
// They must not duplicate the production section encoder.
package isla_test

import (
	"fmt"
	"strconv"
	"strings"
)

type renderedARM64Section struct {
	address  uint64
	writable bool
	bytes    []byte
}

func parseARM64Sections(source string) ([]renderedARM64Section, error) {
	lines := strings.Split(source, "\n")
	sections := make([]renderedARM64Section, 0)
	for index := 0; index < len(lines); index++ {
		if !strings.HasPrefix(lines[index], "[section.region_") {
			continue
		}
		section, next, err := parseARM64Section(lines, index)
		if err != nil {
			return nil, err
		}
		sections = append(sections, section)
		index = next
	}
	return sections, nil
}

func parseARM64Section(lines []string, index int) (renderedARM64Section, int, error) {
	if index+3 >= len(lines) || !strings.HasPrefix(lines[index+1], "address = ") || !strings.HasPrefix(lines[index+2], "writable = ") || lines[index+3] != "code = \"\"\"" {
		return renderedARM64Section{}, index, fmt.Errorf("malformed generated section header")
	}
	addressText, err := strconv.Unquote(strings.TrimPrefix(lines[index+1], "address = "))
	if err != nil {
		return renderedARM64Section{}, index, err
	}
	address, err := strconv.ParseUint(strings.TrimPrefix(addressText, "0x"), 16, 64)
	if err != nil {
		return renderedARM64Section{}, index, err
	}
	writable, err := strconv.ParseBool(strings.TrimPrefix(lines[index+2], "writable = "))
	if err != nil {
		return renderedARM64Section{}, index, err
	}
	return parseARM64SectionBytes(lines, index+4, address, writable)
}

func parseARM64SectionBytes(lines []string, index int, address uint64, writable bool) (renderedARM64Section, int, error) {
	section := renderedARM64Section{address: address, writable: writable}
	for ; index < len(lines); index++ {
		line := strings.TrimSpace(lines[index])
		if line == "\"\"\"" {
			return section, index, nil
		}
		var value uint64
		if _, err := fmt.Sscanf(line, ".byte 0x%x", &value); err != nil || value > 0xff {
			return renderedARM64Section{}, index, fmt.Errorf("malformed generated byte %q", line)
		}
		section.bytes = append(section.bytes, byte(value))
	}
	return renderedARM64Section{}, index, fmt.Errorf("unterminated generated section")
}
