// Executable program values bind generated Isla input to one loaded ELF.
// Callers receive a copy of the generated bytes and its measured identity.
package isla

import "github.com/HyperMarble/hyperray/machine"

// Program contains generated Isla input and its source identity.
type Program struct {
	content             []byte
	digest              string
	imageDigest         string
	profile             string
	entryAddress        uint64
	functionStart       uint64
	functionEnd         uint64
	returnAddress       uint64
	postResetRegisters  []RegisterValue
	threadEntries       []ThreadEntry
	threadIdentity      string
	instructionCount    uint64
	loadedByteCount     uint64
	instructions        []machine.Instruction
	memoryProfile       MemoryProfile
	memoryInput         *ARM64MemoryInput
	memoryIdentity      string
	memoryObservations  []MemoryObservation
	typedInitialState   bool
	forbiddenModelCalls []string
}

// BuildProgram converts one accepted ELF into data-only Isla input.
func BuildProgram(elfContent []byte, maximumLoadedBytes uint64, boundary ProgramBoundary) (Program, error) {
	image, err := machine.Load(elfContent, maximumLoadedBytes)
	if err != nil {
		return Program{}, err
	}
	content, err := renderProgram(image, boundary)
	if err != nil {
		return Program{}, err
	}
	program := newProgram(image, content, image.Instructions)
	program.threadEntries, err = validatedThreads(image, boundary)
	if err != nil {
		return Program{}, err
	}
	program.threadIdentity = threadEntryIdentity(program.threadEntries)
	program.memoryProfile = boundary.MemoryProfile
	program.typedInitialState = len(boundary.InitialState) != 0
	program.forbiddenModelCalls = append([]string(nil), boundary.ForbiddenModelCalls...)
	return program, nil
}

// Content returns an independent copy of the generated Isla input.
func (program Program) Content() []byte {
	return append([]byte(nil), program.content...)
}

func (program Program) Digest() string               { return program.digest }
func (program Program) ImageDigest() string          { return program.imageDigest }
func (program Program) EntryAddress() uint64         { return program.entryAddress }
func (program Program) ThreadEntries() []ThreadEntry { return copyThreadEntries(program.threadEntries) }
func (program Program) ThreadCount() uint64 {
	if len(program.threadEntries) == 0 && program.entryAddress != 0 {
		return 1
	}
	return uint64(len(program.threadEntries))
}
func (program Program) InstructionCount() uint64 {
	return program.instructionCount
}
func (program Program) LoadedByteCount() uint64 { return program.loadedByteCount }
