[package]
name = "rechecker"
version = "0.1.0"
edition = "2021"

[lib]
path = "lib.rs"

[dependencies]
libloading = "0.9"
solver = { path = "../solver" }



[[test]]
name = "placed_test"
path = "tests/placed_test.rs"

[[test]]
name = "shapes_test"
path = "tests/shapes_test.rs"

[[test]]
name = "agreement_test"
path = "tests/agreement_test.rs"
