package main

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/spf13/cobra"

	"github.com/HyperMarble/ray/internal/semanticir"
)

// newBridgesGenCmd generates the probe files the spec implies -- one per
// rule-group, named so per-row attribution works without any mapping file:
// wit_<operation>__<key>.py watches the rows of that operation matching that
// key. Ray writes the whole file from the compiled spec: the rule IDs, the
// conditions, the required outcomes, and the observation contract. The one
// line ray cannot know -- how to call the system under test -- is a TODO the
// task author fills, because that knowledge is the task's, not ray's.
// Existing files are never touched.
func newBridgesGenCmd() *cobra.Command {
	return &cobra.Command{
		Use:          "bridges-gen <task-dir>",
		Hidden:       true,
		Short:        "Generate the probe files the spec implies; author fills one calling line each",
		Args:         cobra.ExactArgs(1),
		SilenceUsage: true,
		RunE: func(cmd *cobra.Command, args []string) error {
			taskDir, err := filepath.Abs(args[0])
			if err != nil {
				return err
			}
			task, err := compileTaskDir(taskDir)
			if err != nil {
				return err
			}
			outcomes := map[string]semanticir.ObservableOutcome{}
			for _, outcome := range task.Outcomes {
				outcomes[outcome.ID] = outcome
			}
			bridgesDir := filepath.Join(taskDir, "bridges")
			if err := os.MkdirAll(bridgesDir, 0o755); err != nil {
				return err
			}
			// One probe per (operation, key): rules sharing a key share a
			// probe. Raise-rows are excluded -- the message breaker already
			// covers them without any probe.
			groups := map[string][]semanticir.RequirementCase{}
			for _, requirement := range task.Requirements {
				for _, key := range probeKeys(requirement, outcomes) {
					name := requirement.OperationID + "__" + key
					groups[name] = append(groups[name], requirement)
				}
			}
			// Probes are fully generated: each one feeds the row's own values
			// to the operation's entry file and prints what came back. The
			// entry file -- one per operation, a few lines -- is the only
			// authored piece, the same trust surface Grounding already is.
			probes, entries, existing := 0, 0, 0
			seenOps := map[string]bool{}
			for name, requirements := range groups {
				requirement := requirements[0]
				operation := requirement.OperationID
				entryPath := filepath.Join(bridgesDir, "entry_"+operation+".py")
				if _, err := os.Stat(entryPath); err != nil && !seenOps[operation] {
					if err := os.WriteFile(entryPath, []byte(entryStub(operation, requirements)), 0o755); err != nil {
						return err
					}
					entries++
					fmt.Fprintf(cmd.OutOrStdout(), "entry stub  entry_%s.py (author fills ~5 lines, once)\n", operation)
				}
				seenOps[operation] = true
				path := filepath.Join(bridgesDir, "wit_"+name+".py")
				if _, err := os.Stat(path); err == nil {
					existing++
					continue
				}
				if err := os.WriteFile(path, []byte(generatedProbe(operation, requirement)), 0o755); err != nil {
					return err
				}
				probes++
			}
			fmt.Fprintf(cmd.OutOrStdout(), "\n%d probe(s) generated by ray, %d already existed, %d entry stub(s) for the author\n", probes, existing, entries)
			return nil
		},
	}
}

// probeKeys names the probe(s) that watch one rule: its required string
// label, or for concrete-outcome rules each condition value, so the file
// name alone carries the attribution.
func probeKeys(requirement semanticir.RequirementCase, outcomes map[string]semanticir.ObservableOutcome) []string {
	for _, outcomeID := range requirement.RequiredOutcomes {
		outcome := outcomes[outcomeID]
		if outcome.Kind == semanticir.OutcomeReturn && outcome.Value != nil && outcome.Value.Type == semanticir.TypeString {
			return []string{outcome.Value.String}
		}
		// A raise-row's probe watches the error path; all combos sharing the
		// message share one probe, named by the message itself.
		if outcome.Kind == semanticir.OutcomeRaise && outcome.Message != "" {
			return []string{slug(outcome.Message)}
		}
	}
	var keys []string
	for _, name := range sortedKeys(requirement.Conditions) {
		keys = append(keys, requirement.Conditions[name])
	}
	if len(keys) == 0 {
		keys = []string{"any"}
	}
	return keys[:1]
}

func slug(text string) string {
	var out []rune
	for _, r := range strings.ToLower(text) {
		switch {
		case r >= 'a' && r <= 'z' || r >= '0' && r <= '9':
			out = append(out, r)
		case len(out) > 0 && out[len(out)-1] != '-':
			out = append(out, '-')
		}
	}
	return strings.Trim(string(out), "-")
}

func sortedKeys(values map[string]string) []string {
	var keys []string
	for key := range values {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	return keys
}

// generatedProbe is entirely ray's: it hands the row's declared values to
// the operation's entry and prints the observation. No task knowledge here.
func generatedProbe(operation string, requirement semanticir.RequirementCase) string {
	var conditions strings.Builder
	conditions.WriteString("{")
	for index, key := range sortedKeys(requirement.Conditions) {
		if index > 0 {
			conditions.WriteString(", ")
		}
		conditions.WriteString(fmt.Sprintf("%q: %q", key, requirement.Conditions[key]))
	}
	conditions.WriteString("}")
	return fmt.Sprintf(`#!/usr/bin/env python3
"""Generated by ray. Do not edit: regenerate with ray bridges-gen."""
import sys
sys.path.insert(0, __file__.rsplit("/", 1)[0])
from entry_%s import run

print(run(**%s))
`, operation, conditions.String())
}

// entryStub is the one authored piece per operation: given a row's values,
// call the system under test and return one deterministic description.
func entryStub(operation string, requirements []semanticir.RequirementCase) string {
	return fmt.Sprintf(`#!/usr/bin/env python3
"""Entry for operation %q -- the author's one file for this operation.

run(**values) receives one rule's condition values (e.g. %v).
Call the system under test accordingly and RETURN one deterministic,
printable description of what happened. Same behaviour must return the
same value; changed behaviour must change it. Never print random data.
"""


def run(**values):
    raise SystemExit("TODO(author): call the system for %s and return the observation")
`, operation, requirements[0].Conditions, operation)
}
