(* Name the fixed JIB type and operation constructors. *)
(* Never classify a Sail instruction or source function name. *)
open Libsail
open Jib
[@@@warning "+8"]
[@@@warnerror "+8"]

let of_type = function
  | CT_lint -> "lint"
  | CT_fint _ -> "fint"
  | CT_constant _ -> "constant"
  | CT_lbits -> "lbits"
  | CT_sbits _ -> "sbits"
  | CT_fbits _ -> "fbits"
  | CT_unit -> "unit"
  | CT_bool -> "bool"
  | CT_string -> "string"
  | CT_real -> "real"
  | CT_float _ -> "float"
  | CT_rounding_mode -> "rounding_mode"
  | CT_tup _ -> "tuple"
  | CT_enum _ -> "enum"
  | CT_struct _ -> "struct"
  | CT_variant _ -> "variant"
  | CT_fvector _ -> "fixed_vector"
  | CT_vector _ -> "vector"
  | CT_list _ -> "list"
  | CT_ref _ -> "reference"
  | CT_poly _ -> "polymorphic"
  | CT_memory_writes -> "memory_writes"
  | CT_json -> "json"
  | CT_json_key -> "json_key"

let of_operation = function
  | Bnot -> "boolean_not"
  | Bor -> "boolean_or"
  | Band -> "boolean_and"
  | List_hd -> "list_head"
  | List_tl -> "list_tail"
  | List_is_empty -> "list_is_empty"
  | Eq -> "equal"
  | Neq -> "not_equal"
  | Ite -> "if_then_else"
  | String_eq -> "string_equal"
  | Index _ -> "index"
  | Ilt -> "integer_less_than"
  | Ilteq -> "integer_less_or_equal"
  | Igt -> "integer_greater_than"
  | Igteq -> "integer_greater_or_equal"
  | Iadd -> "integer_add"
  | Isub -> "integer_subtract"
  | Unsigned _ -> "unsigned"
  | Signed _ -> "signed"
  | Bvnot -> "bitvector_not"
  | Bvor -> "bitvector_or"
  | Bvand -> "bitvector_and"
  | Bvxor -> "bitvector_xor"
  | Bvadd -> "bitvector_add"
  | Bvsub -> "bitvector_subtract"
  | Bvaccess -> "bitvector_access"
  | Concat -> "concatenate"
  | Zero_extend _ -> "zero_extend"
  | Sign_extend _ -> "sign_extend"
  | Slice _ -> "slice"
  | Sslice _ -> "subrange_slice"
  | Set_slice -> "set_slice"
  | Replicate _ -> "replicate"
