[package]
name = "language-rust"
version = "0.1.0"
edition = "2021"

[lib]
path = "lib.rs"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sha2 = "0.10"


[[test]]
name = "record_test"
path = "tests/record_test.rs"

[[test]]
name = "project_test"
path = "tests/project_test.rs"

[[test]]
name = "toolchain_test"
path = "tests/toolchain_test.rs"

[[test]]
name = "os_test"
path = "tests/os_test.rs"

[[test]]
name = "cargo_build_test"
path = "tests/cargo_build_test.rs"

[[test]]
name = "locked_test"
path = "tests/locked_test.rs"
