[package]
name = "language-rust"
version = "0.1.0"
edition = "2021"

[lib]
path = "lib.rs"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sha2 = "0.10"


[[test]]
name = "record_test"
path = "tests/record_test.rs"

[[test]]
name = "project_test"
path = "tests/project_test.rs"

[[test]]
name = "toolchain_test"
path = "tests/toolchain_test.rs"

[[test]]
name = "os_test"
path = "tests/os_test.rs"

[[test]]
name = "cargo_build_test"
path = "tests/cargo_build_test.rs"

[[test]]
name = "locked_test"
path = "tests/locked_test.rs"

[[test]]
name = "build_record_test"
path = "tests/build_record_test.rs"

[[test]]
name = "choice_test"
path = "tests/choice_test.rs"

[[test]]
name = "features_test"
path = "tests/features_test.rs"

[[test]]
name = "environment_test"
path = "tests/environment_test.rs"

[[test]]
name = "native_code_test"
path = "tests/native_code_test.rs"

[[test]]
name = "c_toolchain_test"
path = "tests/c_toolchain_test.rs"

[[test]]
name = "debug_info_test"
path = "tests/debug_info_test.rs"

[[test]]
name = "compiler_printout_test"
path = "tests/compiler_printout_test.rs"

[[test]]
name = "config_file_test"
path = "tests/config_file_test.rs"
