// Package bridges generates probe sources per language: everything except
// the author's entry, which is the one piece that knows how to call the
// system under test. Compiled languages get one shared harness plus a shell
// wrapper per rule-group; all failures print as "TYPE: message".
package bridges

import (
	"fmt"
	"sort"
	"strings"
)

// SortedConditionKeys orders a rule's condition names deterministically.
func SortedConditionKeys(conditions map[string]string) []string {
	var keys []string
	for key := range conditions {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	return keys
}

// PythonProbe is the per-rule-group probe script.
func PythonProbe(operation string, conditions map[string]string) string {
	var pairs strings.Builder
	pairs.WriteString("{")
	for index, key := range SortedConditionKeys(conditions) {
		if index > 0 {
			pairs.WriteString(", ")
		}
		pairs.WriteString(fmt.Sprintf("%q: %q", key, conditions[key]))
	}
	pairs.WriteString("}")
	return fmt.Sprintf(`#!/usr/bin/env python3
"""Generated by hyperray. Do not edit: regenerate with hyperray bridges-gen."""
import sys
sys.path.insert(0, __file__.rsplit("/", 1)[0])
from entry_%s import run

print(run(**%s))
`, operation, pairs.String())
}

// PythonEntryStub is the author's one file per operation (Python tasks).
func PythonEntryStub(operation string, conditions map[string]string) string {
	return fmt.Sprintf(`#!/usr/bin/env python3
"""Entry for operation %q -- the author's one file for this operation.

run(**values) receives one rule's condition values (e.g. %v).
Call the system under test accordingly and RETURN one deterministic,
printable description of what happened. Same behaviour must return the
same value; changed behaviour must change it. Never print random data.
"""


def run(**values):
    raise SystemExit("TODO(author): call the system for %s and return the observation")
`, operation, conditions, operation)
}

// WrapperScript is the per-rule-group shell file for compiled languages: it
// invokes the shared harness with the operation and the rule's values as
// key=value arguments. It lives in the task's bridges/ directory and runs
// with the source root as working directory.
func WrapperScript(language, operation string, conditions map[string]string) string {
	var arguments []string
	arguments = append(arguments, shellQuote(operation))
	for _, key := range SortedConditionKeys(conditions) {
		arguments = append(arguments, shellQuote(key+"="+conditions[key]))
	}
	joined := strings.Join(arguments, " ")
	switch language {
	case "rust":
		return fmt.Sprintf(`#!/bin/sh
# Generated by hyperray. Do not edit: regenerate with hyperray bridges-gen.
exec cargo run --quiet --example hyperray_probes -- %s
`, joined)
	default: // cpp
		return fmt.Sprintf(`#!/bin/sh
# Generated by hyperray. Do not edit: regenerate with hyperray bridges-gen.
# HYPERRAY_PROBE_BUILD overrides the compile line when the entry needs the
# project's headers, libraries, or build flags.
here="$(cd "$(dirname "$0")" && pwd)"
if [ ! -x "$here/hyperray_probes" ] || [ "$here/hyperray_probes.cpp" -nt "$here/hyperray_probes" ] || [ "$here/hyperray_entry.cpp" -nt "$here/hyperray_probes" ]; then
    ${HYPERRAY_PROBE_BUILD:-c++ -std=c++17 "$here/hyperray_probes.cpp" -o "$here/hyperray_probes"} || exit 1
fi
exec "$here/hyperray_probes" %s
`, joined)
	}
}

// RustHarness is the shared generated probe binary source. It parses
// operation and key=value arguments, calls the author's run, and prints one
// observation line; a panic prints as "panic: message" so raise-rows keep
// their message-matching contract.
func RustHarness() string {
	return `// Generated by hyperray. Do not edit: regenerate with hyperray bridges-gen.
include!("hyperray_entry.rs");

fn main() {
    let arguments: Vec<String> = std::env::args().skip(1).collect();
    let operation = arguments.first().cloned().unwrap_or_default();
    let values: Vec<(String, String)> = arguments[1..]
        .iter()
        .map(|pair| {
            let mut parts = pair.splitn(2, '=');
            (
                parts.next().unwrap_or("").to_string(),
                parts.next().unwrap_or("").to_string(),
            )
        })
        .collect();
    let outcome = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| run(&operation, &values)));
    match outcome {
        Ok(observation) => println!("{observation}"),
        Err(payload) => {
            let message = payload
                .downcast_ref::<String>()
                .cloned()
                .or_else(|| payload.downcast_ref::<&str>().map(|text| text.to_string()))
                .unwrap_or_default();
            println!("panic: {message}");
        }
    }
}
`
}

// RustEntryStub is the author's one file for a Rust task.
func RustEntryStub() string {
	return `// Entry for this task's probes -- the author's one file.
//
// run receives the operation name and one rule's condition values as
// (key, value) pairs. Call the system under test accordingly and RETURN
// one deterministic observation string. Panic (or return an error text)
// where the rule expects the error path; the harness prints a panic as
// "panic: message". Same behaviour must return the same value; changed
// behaviour must change it.

pub fn run(operation: &str, values: &[(String, String)]) -> String {
    let _ = values;
    panic!("TODO(author): call the system for {operation} and return the observation");
}
`
}

// CppHarness is the shared generated probe binary source for C++ tasks. A
// thrown std::exception prints as "DemangledType: what()"; anything else as
// "unknown exception".
func CppHarness() string {
	return `// Generated by hyperray. Do not edit: regenerate with hyperray bridges-gen.
#include "hyperray_entry.cpp"

#include <cstdio>
#include <cstdlib>
#include <exception>
#include <string>
#include <typeinfo>
#include <utility>
#include <vector>

#if defined(__GNUG__)
#include <cxxabi.h>
static std::string hyperray_type_name(const std::type_info &info) {
    int status = 0;
    char *demangled = abi::__cxa_demangle(info.name(), nullptr, nullptr, &status);
    if (status == 0 && demangled != nullptr) {
        std::string name(demangled);
        std::free(demangled);
        return name;
    }
    return info.name();
}
#else
static std::string hyperray_type_name(const std::type_info &info) { return info.name(); }
#endif

int main(int argc, char **argv) {
    std::string operation = argc > 1 ? argv[1] : "";
    std::vector<std::pair<std::string, std::string>> values;
    for (int index = 2; index < argc; ++index) {
        std::string pair = argv[index];
        std::size_t equals = pair.find('=');
        if (equals == std::string::npos) {
            values.push_back({pair, ""});
        } else {
            values.push_back({pair.substr(0, equals), pair.substr(equals + 1)});
        }
    }
    try {
        std::printf("%s\n", run(operation, values).c_str());
    } catch (const std::exception &error) {
        std::printf("%s: %s\n", hyperray_type_name(typeid(error)).c_str(), error.what());
    } catch (...) {
        std::printf("unknown exception\n");
    }
    return 0;
}
`
}

// CppEntryStub is the author's one file for a C++ task.
func CppEntryStub() string {
	return `// Entry for this task's probes -- the author's one file.
//
// run receives the operation name and one rule's condition values as
// (key, value) pairs. Call the system under test accordingly and RETURN
// one deterministic observation string. Throw where the rule expects the
// error path; the harness prints "Type: message". Same behaviour must
// return the same value; changed behaviour must change it. If calling the
// project needs headers or libraries, include them here and set
// HYPERRAY_PROBE_BUILD in hyperray.toml's environment to the full compile line.

#include <stdexcept>
#include <string>
#include <utility>
#include <vector>

std::string run(const std::string &operation,
                const std::vector<std::pair<std::string, std::string>> &values) {
    (void)values;
    throw std::runtime_error("TODO(author): call the system for " + operation +
                             " and return the observation");
}
`
}

func shellQuote(text string) string {
	return "'" + strings.ReplaceAll(text, "'", `'\''`) + "'"
}
